const CATALOG_ITEM_IMAGE = 'CATALOG_ITEM_IMAGE';
const STORE_IMAGE = 'STORE_IMAGE';
const STORE_BACKGROUND = 'STORE_BACKGROUND';

module.exports = { CATALOG_ITEM_IMAGE, STORE_IMAGE, STORE_BACKGROUND };
